package cli

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

// starterConfig is the annotated starter .gitl.yaml written by `gitl init`.
// Every active key mirrors the corresponding default in
// internal/config.defaults() exactly, so the generated file is a no-op until
// edited (least surprise) and is guaranteed to round-trip through config.Load
// (asserted by TestInitRoundTripsThroughLoader). api_key is deliberately NOT a
// YAML key here — keys come from the GITL_API_KEY env var and are never
// committed. output.color is omitted: it is a dead knob until Roadmap U1 lands.
const starterConfig = `# .gitl.yaml — gitl team policy (committed at the repo root, shared by the team).
# Generated by ` + "`gitl init`" + `. Precedence (highest wins):
#   flag > env (GITL_*) > .gitl.yaml (cwd) > .gitl.yaml (repo root) > ~/.config/gitl/config.yaml
# Full reference: https://github.com/akomyagin/gitl#configuration

llm:
  # Provider for AI review. One of: openai | ollama | azure_openai | anthropic | gemini
  provider: "openai"
  # Model name (also used for cost estimation). Override per-provider below.
  model: "gpt-4o-mini"
  # api_key: leave unset here — supply it via the GITL_API_KEY env var, never commit it.
  # With no key, gitl runs in deterministic OFFLINE mode (no network, no cost).

  # --- Alternative providers (uncomment ONE block and adjust) ---
  # Ollama (local/self-hosted, no key, free):
  #   provider: "ollama"
  #   base_url: "http://localhost:11434/v1"
  #   model: "llama3.1"
  # Anthropic (native Claude):
  #   provider: "anthropic"
  #   model: "claude-sonnet-4-6"
  # Google Gemini:
  #   provider: "gemini"
  #   model: "gemini-2.5-flash"
  # Azure OpenAI:
  #   provider: "azure_openai"
  #   model: "gpt-4o-mini"
  #   azure_openai:
  #     endpoint: "https://<resource>.openai.azure.com"
  #     deployment: "<deployment-name>"
  #     api_version: "2024-08-01-preview"

policy:
  # CI gating threshold: never | low | medium | high.
  # "never" (default) only reports; set "high" to fail CI on high-risk reviews.
  fail_on: "never"
  # Append each review's risk outcome to a LOCAL risk-history log (digest reads it
  # back as a "Risk trend" section). Local to your machine; set false to opt out.
  risk_log_enabled: true

diff:
  # Skip these changed paths before building the diff sent to the model.
  exclude_globs:
    - "*.lock"
    - "*.min.js"
    - "vendor/**"
    - "*.svg"

cache:
  # On-disk cache of model responses (identical diffs reuse the result, no API call).
  enabled: true
  ttl_hours: 24
  # Opt-in shared HTTP KV cache for CI cold starts (off by default; gitl hosts nothing):
  # remote:
  #   url: "https://cache.example.com/gitl"
  #   token_env: "GITL_REMOTE_CACHE_TOKEN"
  #   timeout_ms: 3000

# Optional cost guard (uncomment to cap per-review spend):
# cost:
#   max_cost_usd: 0.50   # block if the estimated cost exceeds this (<=0 disables)
#   warn_at_usd:  0.10

# Optional output default (md | text | json):
# output:
#   format: "md"
`

// newInitCmd builds the `gitl init` command. gf is threaded through for
// signature uniformity with the other subcommands even though init writes
// config rather than reading it (no loadConfig call).
func newInitCmd(gf *globalFlags) *cobra.Command {
	var (
		force  bool
		output string
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "generate a starter .gitl.yaml with sensible defaults and inline comments",
		Long: "init writes an annotated starter .gitl.yaml — the committed repo-root team\n" +
			"policy (provider, risk threshold, excluded paths, cache policy) — with the\n" +
			"built-in defaults and inline comments explaining each knob.\n\n" +
			"Non-interactive: no prompts, no network. The default target is the git repo\n" +
			"root (falling back to the current directory outside a git repo); --output\n" +
			"writes elsewhere. An existing file is never overwritten without --force.\n\n" +
			"The generated file round-trips through gitl's own config loader, so it is\n" +
			"valid as-is and a no-op until edited.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			_ = gf // reserved for --verbose slog plumbing; init loads no config
			return runInit(cmd, force, output)
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing file at the target path")
	cmd.Flags().StringVarP(&output, "output", "o", "", "output path (default: <repo root>/.gitl.yaml, or ./.gitl.yaml outside a git repo)")
	return cmd
}

// runInit resolves the target path, applies the overwrite guard, and writes
// the starter template.
func runInit(cmd *cobra.Command, force bool, output string) error {
	target := output
	if target != "" {
		target = filepath.Clean(target)
	} else {
		root := discoverRepoRoot(cmd.Context())
		if root == "" {
			// Mirrors the discoverRepoRoot contract: root discovery must never
			// fail a command — fall back to the current working directory.
			fmt.Fprintln(cmd.ErrOrStderr(), "gitl: not inside a git repository; writing .gitl.yaml to the current directory")
			root = "."
		}
		target = filepath.Join(root, ".gitl.yaml")
	}

	// Overwrite guard. The stat-then-write race (TOCTOU) is acceptable here:
	// this is an interactive dev-onboarding command, not a security boundary,
	// and O_EXCL would complicate the --force path.
	if _, err := os.Stat(target); err == nil {
		if !force {
			return fmt.Errorf("%s already exists; pass --force to overwrite", target)
		}
		slog.Warn("overwriting existing config", "path", target)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", target, err)
	}

	if err := os.WriteFile(target, []byte(starterConfig), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", target, err)
	}
	cmd.Printf("wrote starter config to %s\nedit it, then run: gitl review HEAD~5..HEAD\n", target)
	return nil
}
