package llm

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/akomyagin/gitl/internal/gitlog"
)

// Offline is a deterministic, network-free Provider used when no API key is
// configured. Given the same commits and diff it always produces the same
// Markdown review — no time-based randomness, no external calls — so tests
// stay stable.
//
// It is a genuinely useful fallback (not a "no key" stub): it summarizes commit
// subjects, lists changed files grouped by status, and reports rough size
// stats. Structured risk-scoring (low|medium|high) is intentionally not
// produced here — that lands in Этап 2 (see docs/TECHNICAL_PLAN.md §6).
type Offline struct {
	commits []gitlog.Commit
	diff    string
}

var _ Provider = (*Offline)(nil)

// NewOffline builds an Offline provider from the structured review input. The
// provider works from this data directly; the Request passed to Complete is
// ignored (there is no model to prompt).
func NewOffline(commits []gitlog.Commit, diff string) *Offline {
	return &Offline{commits: commits, diff: diff}
}

// Complete returns a deterministic Markdown review. The ctx is honored for
// cancellation; req is unused (offline has no model to prompt).
func (o *Offline) Complete(ctx context.Context, _ Request) (Response, error) {
	if err := ctx.Err(); err != nil {
		return Response{}, err
	}
	return Response{Content: o.render()}, nil
}

// render builds the Markdown summary. It is pure and deterministic.
func (o *Offline) render() string {
	var b strings.Builder

	b.WriteString("# Code review (offline)\n\n")
	b.WriteString("> Generated by the deterministic offline provider (no LLM key configured). ")
	b.WriteString("For an AI-authored review, set `GITL_API_KEY` or `llm.api_key`.\n\n")

	o.writeSummary(&b)
	o.writeCommits(&b)
	o.writeFiles(&b)
	o.writeDiffStats(&b)

	return b.String()
}

// writeSummary writes the high-level counts.
func (o *Offline) writeSummary(b *strings.Builder) {
	fileCount, adds, dels, mods, renames := o.fileStats()
	b.WriteString("## Summary\n\n")
	if len(o.commits) == 0 {
		b.WriteString("No commits found in the given range.\n\n")
		return
	}
	fmt.Fprintf(b, "- **Commits:** %d\n", len(o.commits))
	fmt.Fprintf(b, "- **Files touched:** %d (added %d, modified %d, deleted %d, renamed %d)\n",
		fileCount, adds, mods, dels, renames)
	fmt.Fprintf(b, "- **Diff size:** ~%s\n\n", humanBytes(len(o.diff)))
}

// writeCommits lists the commit subjects (and authors) in order.
func (o *Offline) writeCommits(b *strings.Builder) {
	if len(o.commits) == 0 {
		return
	}
	b.WriteString("## Commits\n\n")
	for _, c := range o.commits {
		short := c.Hash
		if len(short) > 7 {
			short = short[:7]
		}
		fmt.Fprintf(b, "- `%s` %s — %s\n", short, c.Subject, c.Author)
	}
	b.WriteString("\n")
}

// writeFiles lists changed files grouped by status, deterministically sorted.
func (o *Offline) writeFiles(b *strings.Builder) {
	// Deduplicate files across commits. git log yields commits newest-first,
	// so the first time a path is seen carries its most recent status; keep
	// that and ignore older entries. Output is sorted by path for determinism.
	statusByPath := map[string]gitlog.FileChange{}
	for _, c := range o.commits {
		for _, f := range c.Files {
			if _, seen := statusByPath[f.Path]; !seen {
				statusByPath[f.Path] = f
			}
		}
	}
	if len(statusByPath) == 0 {
		return
	}

	paths := make([]string, 0, len(statusByPath))
	for p := range statusByPath {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	b.WriteString("## Changed files\n\n")
	for _, p := range paths {
		f := statusByPath[p]
		label := statusLabel(f.Status)
		if f.Old != "" {
			fmt.Fprintf(b, "- **%s** `%s` → `%s`\n", label, f.Old, f.Path)
		} else {
			fmt.Fprintf(b, "- **%s** `%s`\n", label, f.Path)
		}
	}
	b.WriteString("\n")
}

// writeDiffStats reports rough diff line stats parsed from unified diff text.
func (o *Offline) writeDiffStats(b *strings.Builder) {
	if strings.TrimSpace(o.diff) == "" {
		return
	}
	var added, removed int
	for _, line := range strings.Split(o.diff, "\n") {
		switch {
		case strings.HasPrefix(line, "+++"), strings.HasPrefix(line, "---"):
			// file headers, not content changes
		case strings.HasPrefix(line, "+"):
			added++
		case strings.HasPrefix(line, "-"):
			removed++
		}
	}
	b.WriteString("## Diff stats\n\n")
	fmt.Fprintf(b, "- Lines added: %d\n", added)
	fmt.Fprintf(b, "- Lines removed: %d\n\n", removed)
	b.WriteString("_Offline mode does not analyze diff semantics; connect an LLM for a substantive review._\n")
}

// fileStats aggregates per-status file counts across all commits, deduplicated
// by path. Commits are newest-first, so the first status seen per path is the
// most recent one.
func (o *Offline) fileStats() (total, adds, dels, mods, renames int) {
	statusByPath := map[string]string{}
	for _, c := range o.commits {
		for _, f := range c.Files {
			if _, seen := statusByPath[f.Path]; !seen {
				statusByPath[f.Path] = f.Status
			}
		}
	}
	for _, status := range statusByPath {
		total++
		switch {
		case strings.HasPrefix(status, "A"):
			adds++
		case strings.HasPrefix(status, "D"):
			dels++
		case strings.HasPrefix(status, "R"):
			renames++
		default:
			mods++
		}
	}
	return total, adds, dels, mods, renames
}

// statusLabel maps a git status code to a human-readable label.
func statusLabel(status string) string {
	switch {
	case strings.HasPrefix(status, "A"):
		return "added"
	case strings.HasPrefix(status, "D"):
		return "deleted"
	case strings.HasPrefix(status, "M"):
		return "modified"
	case strings.HasPrefix(status, "R"):
		return "renamed"
	case strings.HasPrefix(status, "C"):
		return "copied"
	default:
		return status
	}
}

// humanBytes renders a byte count in a compact, deterministic form.
func humanBytes(n int) string {
	switch {
	case n < 1024:
		return fmt.Sprintf("%d B", n)
	case n < 1024*1024:
		return fmt.Sprintf("%.1f KiB", float64(n)/1024)
	default:
		return fmt.Sprintf("%.1f MiB", float64(n)/(1024*1024))
	}
}
